matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      dist: trusty
  allow_failures:
    - os: linux
sudo: required
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - swift build && swift test
